### PR TITLE
Fix ImGui assertions in built game UI

### LINKED ISSUE #752: Built game can assert in ImGui NewFrame: Invalid style setting (WindowMinSize)
## Summary
Launching a built game can trigger this assertion:

`Assertion failed: g.Style.WindowMinSize.x >= 1.0f && g.Style.WindowMinSize.y >= 1.0f && "Invalid style setting!"
(Dependencies/ImGui/src/imgui.cpp, line 11510)`

## Steps to reproduce
1. Build a game from OvEditor.
2. Launch the produced executable.
3. In some UI states, the application asserts at ImGui NewFrame.

## Expected behavior
The built game should start without ImGui style assertions.

## Actual behavior
The game asserts at startup with `Invalid style setting (WindowMinSize)`.

## Suspected root cause
In `OvUI::Panels::PanelUndecorated`:
- `ImGuiStyleVar_WindowMinSize` is pushed with `{0, 0}`.
- `ImGui::End()` is not called when `ImGui::Begin(...)` returns `false`.

File:
- `Sources/OvUI/src/OvUI/Panels/PanelUndecorated.cpp`

This may leave ImGui in an invalid state and violate style sanity checks (`WindowMinSize >= 1.0f`).

### PR DESCRIPTION
**Pull request by Gopmyc**
## Description
Fixes two ImGui runtime assertions that were occurring in built games:
- `Invalid style setting` on `WindowMinSize`
- `Missing End()`

Changes made:
- In `PanelUndecorated`, set `ImGuiStyleVar_WindowMinSize` to a valid value (`{1.0f, 1.0f}`).
- In `PanelUndecorated`, ensure window scope is properly balanced with `Begin()`/`End()` and `PushStyleVar()`/`PopStyleVar()`.
- In `UIManager`, initialize UI state members (`m_scale`, `m_dpiAware`, `m_dockingState`) to deterministic defaults to avoid undefined style scaling at startup.

Scope is intentionally minimal and limited to:
- `Sources/OvUI/src/OvUI/Panels/PanelUndecorated.cpp`
- `Sources/OvUI/include/OvUI/Core/UIManager.h`

## Related Issue(s)
Fixes #752

## Review Guidance
Please review commit-by-commit:
1. Valid ImGui `WindowMinSize` in `PanelUndecorated`.
2. Balanced ImGui window/style stack in `PanelUndecorated`.
3. Safe default initialization for UI manager scale-related state.

Expected result:
- Built game starts without ImGui assertion on `WindowMinSize`.
- No `Missing End()` assertion during frame end.

## Screenshots/GIFs
N/A (runtime stability fix, no visual UI change expected)

## AI Usage Disclosure
Debugging

## Checklist
- [x] My code follows the project's code style guidelines
- [ ] ~~When applicable, I have commented my code, particularly in hard-to-understand areas~~
- [ ] ~~When applicable, I have updated the documentation accordingly~~
- [x] My changes don't generate new warnings or errors
- [x] I have reviewed and take responsibility for all code in this PR (including any AI-assisted contributions)

### CODE REVIEW

File: Sources/OvUI/include/OvUI/Core/UIManager.h [hunk 1]
```diff
@@ -152,10 +152,10 @@ namespace OvUI::Core
 	private:
 		OvWindowing::Window& m_window;
 		OvTools::Eventing::ListenerID m_contentScaleChangedListener;
-		bool m_dockingState;
+		bool m_dockingState = false;
 		Styling::EStyle m_currentStyle;
-		float m_scale;
-		bool m_dpiAware;
+		float m_scale = 1.0f;
+		bool m_dpiAware = true;
```
Comment (adriengivry) [inline Sources/OvUI/include/OvUI/Core/UIManager.h]: This should be `false` by default

**Review by adriengivry — CHANGES_REQUESTED** [review]

File: Sources/OvUI/include/OvUI/Core/UIManager.h (hunk 1 above)
Comment (Gopmyc) [reply Sources/OvUI/include/OvUI/Core/UIManager.h]: Thanks for the catch, good point.
I updated `m_dpiAware` to default to `false` in `UIManager` as requested, while keeping the scale initialization to avoid undefined style values

**Review by adriengivry — APPROVED** [review]
