### PR TITLE
Fixed clear color alpha was set to 0.0f

### LINKED ISSUE #356: Game view's background is grey?
**Description**
Looks like the game view's background is grey instead of blue.

**To Reproduce**
1. Open the editor
2. Focus the game view
3. Notice the issue

**Expected behavior**
If the camera's clear color is set to a color, it should be used.

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by adriengivry**
## Description
For some reason, even though the clear color `w` value (alpha component), was set to `0.0f` (which is the default when constructing a `FVector4` from a `FVector3`, the views would render properly in the editor. After some changes (I'm assuming updating C++ version from 17 to 20), this behaviour changed, and view backgrounds stop being rendered properly.

This PR fixes the issue by enforcing the alpha to be 1.0f.

## Related Issues
Fixes #356

### CODE REVIEW

File: Sources/Overload/OvRendering/src/OvRendering/Core/ABaseRenderer.cpp [hunk 1]
```diff
@@ -58,11 +58,14 @@ void OvRendering::Core::ABaseRenderer::BeginFrame(const Data::FrameDescriptor& p
 	m_basePipelineState = m_driver.CreatePipelineState();
 	SetViewport(0, 0, p_frameDescriptor.renderWidth, p_frameDescriptor.renderHeight);
 
+	OvMaths::FVector4 clearColor = p_frameDescriptor.camera.value().GetClearColor();
+	clearColor.w = 1.0f;
```
Comment (maxbrundev) [inline Sources/Overload/OvRendering/src/OvRendering/Core/ABaseRenderer.cpp:62]: We should maybe construct the FVector4 directly by parameter to enjoy RVO and avoid the temporary clearColor variable 

`
Clear(
	p_frameDescriptor.camera->GetClearColorBuffer(),
	p_frameDescriptor.camera->GetClearDepthBuffer(),
	p_frameDescriptor.camera->GetClearStencilBuffer(),
	{p_frameDescriptor.camera.value().GetClearColor(), 1.0f}
);
`

**Review by litelawliet — APPROVED** [review]

File: Sources/Overload/OvRendering/src/OvRendering/Core/ABaseRenderer.cpp (hunk 1 above)
Comment (adriengivry) [reply Sources/Overload/OvRendering/src/OvRendering/Core/ABaseRenderer.cpp:62]: Yep, that's fair! Good call
