### PR TITLE
Prevent crash when dragging a folder into its own child

### LINKED ISSUE #699: Drag-and-dropping a parent folder onto one of its children crashes
## Description
Overload crashes when a parent folder is being dragged and dropped onto one of its children folder.

## To Reproduce
1. Create folder "A"
2. Create folder "B" as a child of "A"
3. Drag and drop "A" onto "B"
4. Notice crash

## Expected behavior
Similarly to what we do in the hierarchy, we should prevent such behaviour.

### PR DESCRIPTION
**Pull request by Gopmyc**
## Description
This PR fixes a crash in the Asset Browser when a folder is dragged and dropped into one of its own descendants.

The fix adds a local guard in the folder drag-and-drop handler to detect invalid parent->child (or self) moves before filesystem rename/copy operations are executed.  
When such a move is detected, the operation is safely ignored and a warning is logged.

## Related Issue(s)
Fixes #699

## Review Guidance
Please focus review on:
- Folder DDTarget logic in `AssetBrowser.cpp`
- The new path ancestry guard used before move/copy operations
- Regression risk on valid drag/drop scenarios (project/project and engine/project)

## Screenshots/GIFs
N/A (behavioral crash fix; no UI change)

## Checklist
- [x] My code follows the project's code style guidelines
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] ~~I have updated the documentation accordingly~~
- [x] My changes don't generate new warnings or errors

### CODE REVIEW

File: Sources/OvEditor/src/OvEditor/Panels/AssetBrowser.cpp [hunk 1]
```diff
@@ -128,6 +128,31 @@ namespace
...
+			if (parent == current)
+			{
+				break;
+			}
+
+			current = parent;
+		}
+
+		return false;
+	}
```
Comment (adriengivry) [inline Sources/OvEditor/src/OvEditor/Panels/AssetBrowser.cpp:135]: While this works, we could leverage `std::filesystem` power:
```cpp
bool IsPathSameOrDescendant(const std::filesystem::path& p_path, const std::filesystem::path& p_ancestor)
{
	auto rel = p_path.lexically_normal().lexically_relative(p_ancestor.lexically_normal());
	return !rel.empty() && *rel.begin() != "..";
}
```
Make sure it works on Windows, I only tested it on Linux.

**Review by adriengivry — CHANGES_REQUESTED** [review]

File: Sources/OvEditor/src/OvEditor/Panels/AssetBrowser.cpp (hunk 1 above)
Comment (Gopmyc) [reply Sources/OvEditor/src/OvEditor/Panels/AssetBrowser.cpp:135]: Good catch !
I switched it to use lexically_relative as suggested

**Review by adriengivry — APPROVED** [review]
