### PR TITLE
Fix animation list refresh when model changes on skinned renderer

### LINKED ISSUE #687: Animation list not updated after changing model
## Description
When the model change on a `CModelRenderer`, the list of available animation on a `CSkinnedMeshRenderer` is not updated.

## To Reproduce
1. Create a "Character"
2. Change the mesh of the new actor to "Cube"
3. Notice that the "Skinned Mesh Renderer" still has the character's animations in the list

## Expected behavior
The available animation clips should be updated when the model changes.

## Screenshots

Image

### PR DESCRIPTION
**Pull request by Gopmyc**
## Description
This PR fixes an inspector refresh issue where the animation combo box of `CSkinnedMeshRenderer` was not updated after changing the model on `CModelRenderer`.

The fix is local and minimal:
- Keep the existing model/sync logic unchanged
- Rebuild animation combo choices during gather so the list always reflects the current model

This preserves current behavior while ensuring the UI list stays in sync with model changes.

## Related Issue(s)
Fixes #687

## Review Guidance
Please reproduce with:
1. Create a "Character"
2. Change its model to "Cube"
3. Open "Skinned Mesh Renderer" in inspector

Expected now:
- The animation list updates immediately to match the new model
- If no compatible skinned model is present, no stale animation names remain

Code scope:
- `Sources/OvCore/src/OvCore/ECS/Components/CSkinnedMeshRenderer.cpp` only

## Screenshots/GIFs
N/A (UI behavior fix, no visual redesign)

## Checklist
- [x] My code follows the project's code style guidelines
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] ~~I have updated the documentation accordingly~~
- [x] My changes don't generate new warnings or errors

### CODE REVIEW

File: Sources/OvCore/src/OvCore/ECS/Components/CSkinnedMeshRenderer.cpp [hunk 1]
```diff
@@ -404,16 +404,18 @@ void OvCore::ECS::Components::CSkinnedMeshRenderer::OnInspector(OvUI::Internal::
...
-	animDispatcher.RegisterGatherer([this]
+	animDispatcher.RegisterGatherer([this, &animationChoice]
 	{
+		animationChoice.choices.clear();
+		animationChoice.choices.emplace(-1, "<None>");
+
+		for (size_t i = 0; i < m_animationNames.size(); ++i)
+		{
+			animationChoice.choices.emplace(static_cast<int>(i), m_animationNames[i]);
+		}
```
Comment (adriengivry) [inline Sources/OvCore/src/OvCore/ECS/Components/CSkinnedMeshRenderer.cpp:417]: This isn't ideal because it recreates the list every frame..... but whatever, good enough 🤣

**Review by adriengivry — APPROVED** [review]
