### PR TITLE
Fix Crash when deleting a folder outside of Overload and trying to expand it afterwards#725

### LINKED ISSUE #725: Crash when deleting a folder outside of Overload and trying to expand it afterwards
## Description
Crash when deleting a folder outside of Overload and trying to expand it afterwards.

## To Reproduce
1. Create a folder in Overload
2. Collapse the folder
3. Delete the folder outside of Overload
4. Try expanding the folder in Overload
5. Notice the crash

## Expected behavior
Shouldn't crash

### PR DESCRIPTION
**Pull request by Synyproxy**
## Description
Fixes this bug:
Delete a folder outside of Overload, then try expanding the folder in Overload causes crash.
Now expanding the folder shows error message.
Also fixed deleting that folder from the asset browser.

## Related Issue(s)
https://github.com/Overload-Technologies/Overload/issues/725
Fixes #725

## Review Guidance
When expanding a delete folder, user get's feedback message.
Also fixed deleting that folder from the asset browser

## Checklist

- [x ] My code follows the project's code style guidelines
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have updated the documentation accordingly
- [ x] My changes don't generate new warnings or errors

### CODE REVIEW

**Review by adriengivry — APPROVED** [review]
~~LGTM!~~

**Review by adriengivry — CHANGES_REQUESTED** [review]
Actually contextual actions on the missing folder cause crash (show in explorer, import here, rename...)

Image

**Review by Synyproxy — COMMENTED** [review]
this should handle the other asset browser context menu actions on deleted folder

File: Sources/OvEditor/src/OvEditor/Panels/AssetBrowser.cpp [hunk 1]
```diff
@@ -257,6 +292,12 @@ namespace
 
 		void CreateNewShader(const std::string& p_shaderName, std::optional<const std::string_view> p_type)
 		{
+			if (!ValidateFolderPath(filePath))
+			{
+				ShowPathDeletedError("Create shader");
+				return;
+			}
```
Comment (adriengivry) [inline Sources/OvEditor/src/OvEditor/Panels/AssetBrowser.cpp]: `ValidateFolderPath` could automatically show the error message when it fails.
So we can have something like:
```cpp
if (!ValidateFolderPath(filePath, "Create shader") return;
```

File: Sources/OvEditor/src/OvEditor/Panels/AssetBrowser.cpp [hunk 2]
```diff
@@ -135,6 +136,27 @@ namespace
...
+			MessageBox errorMessage(
+				"Action failed",
+				"Cannot perform this action because the target folder was deleted externally",
+				MessageBox::EMessageType::ERROR,
+				MessageBox::EButtonLayout::OK
+			);
+			return true;
+		}
+		return false;
+	}
```
Comment (adriengivry) [inline Sources/OvEditor/src/OvEditor/Panels/AssetBrowser.cpp]: Probably doesn't need a return value, and could simply log to the console with `OVLOG_ERROR`

**Review by adriengivry — CHANGES_REQUESTED** [review]

**Comment by Gopmyc** [comment]
> this should handle the other asset browser context menu actions on deleted folder

Hi !
Do you need help with this PR ?

**Review by adriengivry — APPROVED** [review]
